##
## Makefile for do-op in /home/baron_l//local/rendu/piscine/Jour_11/do-op
## 
## Made by louis-philippe baron
## Login   <baron_l@epitech.net>
## 
## Started on  Mon Oct 22 18:46:52 2012 louis-philippe baron
## Last update Tue Oct 23 13:50:17 2012 louis-philippe baron
##

SRC=	main.c \
	do_op.c \
	my_put_nbr.c \
	my_getnbr.c \
	my_putstr.c \
	my_putchar.c

OBJ=	$(SRC:.c=.o)

NAME=	do-op

all:	$(OBJ) compile

compile:
	cc -o $(NAME) $(OBJ)

clean:
	@rm -f $(OBJ)