##
## Makefile for Makefile in /home/liagre_c//colle/colle_3
## 
## Made by clement liagre
## Login   <liagre_c@epitech.net>
## 
## Started on  Sat Oct 27 18:24:21 2012 clement liagre
## Last update Sun Oct 28 02:11:19 2012 louis-philippe baron
##

SRC= 	colle.c \
	functions.c \
	line.c \
	compare.c

OBJ=	$(SRC:.c=.o)

NAME=	colle3

all: 	compilation

compilation:	$(OBJ)
	cc -o $(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean:	clean
	rm -f $(NAME)